name: GitHub-Profile-3D-Contrib-Daily

on:
  schedule:
    - cron: "0 18 * * *"  # 18:00 UTC (03:00 JST)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Daily 3D Contribution Chart
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
